# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstuid', models.CharField(max_length=20)),
                ('pclass', models.IntegerField(max_length=1)),
                ('ptel', models.CharField(max_length=20)),
                ('pemail', models.CharField(max_length=50)),
                ('puser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thss.users')),
            ],
        ),
    ]
