# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thss', '0003_auto_20160513_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sstuid', models.CharField(max_length=20)),
                ('scname', models.CharField(max_length=50)),
                ('sscore', models.FloatField(max_length=5)),
                ('sweigh', models.IntegerField()),
                ('sstyle', models.CharField(max_length=20)),
            ],
        ),
    ]
