# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thss', '0005_score_sterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcontent', models.CharField(max_length=100)),
            ],
        ),
    ]
