# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thss', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyear', models.IntegerField()),
                ('tmonth', models.IntegerField()),
                ('tday', models.IntegerField()),
                ('tcontent', models.CharField(max_length=50)),
                ('tuser', models.IntegerField()),
            ],
        ),
    ]
